# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/enlightenment
pkgincludedir = $(includedir)/enlightenment
pkglibdir = $(libdir)/enlightenment
pkglibexecdir = $(libexecdir)/enlightenment
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
am__append_1 = po
am__append_2 = \
po/boldquot.sed \
po/en@boldquot.header \
po/en@quot.header \
po/insert-header.sin \
po/Makefile.in.in \
po/Makevars.template \
po/quot.sed \
po/remove-potcdate.sin \
po/Rules-quot

subdir = .
DIST_COMMON = INSTALL NEWS README AUTHORS ChangeLog \
	$(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in $(srcdir)/enlightenment.spec.in \
	$(srcdir)/enlightenment.pc.in \
	$(top_srcdir)/src/modules/ibar/module.desktop.in \
	$(top_srcdir)/src/modules/dropshadow/module.desktop.in \
	$(top_srcdir)/src/modules/clock/module.desktop.in \
	$(top_srcdir)/src/modules/pager/module.desktop.in \
	$(top_srcdir)/src/modules/battery/module.desktop.in \
	$(top_srcdir)/src/modules/temperature/module.desktop.in \
	$(top_srcdir)/src/modules/notification/module.desktop.in \
	$(top_srcdir)/src/modules/cpufreq/module.desktop.in \
	$(top_srcdir)/src/modules/ibox/module.desktop.in \
	$(top_srcdir)/src/modules/start/module.desktop.in \
	$(top_srcdir)/src/modules/winlist/module.desktop.in \
	$(top_srcdir)/src/modules/fileman/module.desktop.in \
	$(top_srcdir)/src/modules/fileman_opinfo/module.desktop.in \
	$(top_srcdir)/src/modules/conf/module.desktop.in \
	$(top_srcdir)/src/modules/conf_wallpaper2/module.desktop.in \
	$(top_srcdir)/src/modules/conf_theme/module.desktop.in \
	$(top_srcdir)/src/modules/conf_intl/module.desktop.in \
	$(top_srcdir)/src/modules/conf_applications/module.desktop.in \
	$(top_srcdir)/src/modules/conf_display/module.desktop.in \
	$(top_srcdir)/src/modules/conf_shelves/module.desktop.in \
	$(top_srcdir)/src/modules/conf_keybindings/module.desktop.in \
	$(top_srcdir)/src/modules/conf_edgebindings/module.desktop.in \
	$(top_srcdir)/src/modules/conf_window_remembers/module.desktop.in \
	$(top_srcdir)/src/modules/conf_window_manipulation/module.desktop.in \
	$(top_srcdir)/src/modules/conf_menus/module.desktop.in \
	$(top_srcdir)/src/modules/conf_dialogs/module.desktop.in \
	$(top_srcdir)/src/modules/conf_performance/module.desktop.in \
	$(top_srcdir)/src/modules/conf_paths/module.desktop.in \
	$(top_srcdir)/src/modules/conf_interaction/module.desktop.in \
	$(top_srcdir)/src/modules/msgbus/module.desktop.in \
	$(top_srcdir)/src/modules/conf_randr/module.desktop.in \
	$(top_srcdir)/src/modules/gadman/module.desktop.in \
	$(top_srcdir)/src/modules/mixer/module.desktop.in \
	$(top_srcdir)/src/modules/connman/module.desktop.in \
	$(top_srcdir)/src/modules/illume2/doc/illume.dox.in \
	$(top_srcdir)/src/modules/illume2/module.desktop.in \
	$(top_srcdir)/src/modules/illume-home/module.desktop.in \
	$(top_srcdir)/src/modules/illume-home-toggle/module.desktop.in \
	$(top_srcdir)/src/modules/illume-softkey/module.desktop.in \
	$(top_srcdir)/src/modules/illume-keyboard/module.desktop.in \
	$(top_srcdir)/src/modules/illume-indicator/module.desktop.in \
	$(top_srcdir)/src/modules/illume-kbd-toggle/module.desktop.in \
	$(top_srcdir)/src/modules/illume-mode-toggle/module.desktop.in \
	$(top_srcdir)/src/modules/illume-bluetooth/module.desktop.in \
	$(top_srcdir)/src/modules/syscon/module.desktop.in \
	$(top_srcdir)/src/modules/everything/module.desktop.in \
	$(top_srcdir)/src/modules/everything/everything.pc.in \
	$(top_srcdir)/src/modules/systray/module.desktop.in \
	$(top_srcdir)/src/modules/comp/module.desktop.in \
	$(top_srcdir)/src/modules/physics/module.desktop.in \
	$(top_srcdir)/src/modules/quickaccess/module.desktop.in \
	$(top_srcdir)/src/modules/shot/module.desktop.in \
	$(top_srcdir)/src/modules/backlight/module.desktop.in \
	$(top_srcdir)/src/modules/tasks/module.desktop.in \
	$(top_srcdir)/src/modules/xkbswitch/module.desktop.in \
	$(top_srcdir)/src/modules/tiling/module.desktop.in \
	$(top_srcdir)/src/modules/access/module.desktop.in ABOUT-NLS \
	COPYING compile config.guess config.rpath config.sub depcomp \
	install-sh missing ltmain.sh
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ac-plugins.m4 \
	$(top_srcdir)/m4/ac_attribute.m4 \
	$(top_srcdir)/m4/efl_compiler_flag.m4 \
	$(top_srcdir)/m4/efl_doxygen.m4 \
	$(top_srcdir)/m4/efl_path_max.m4 $(top_srcdir)/m4/gettext.m4 \
	$(top_srcdir)/m4/iconv.m4 $(top_srcdir)/m4/intlmacosx.m4 \
	$(top_srcdir)/m4/lib-ld.m4 $(top_srcdir)/m4/lib-link.m4 \
	$(top_srcdir)/m4/lib-prefix.m4 $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/nls.m4 $(top_srcdir)/m4/po.m4 \
	$(top_srcdir)/m4/progtest.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = enlightenment.spec enlightenment.pc \
	src/modules/ibar/module.desktop \
	src/modules/dropshadow/module.desktop \
	src/modules/clock/module.desktop \
	src/modules/pager/module.desktop \
	src/modules/battery/module.desktop \
	src/modules/temperature/module.desktop \
	src/modules/notification/module.desktop \
	src/modules/cpufreq/module.desktop \
	src/modules/ibox/module.desktop \
	src/modules/start/module.desktop \
	src/modules/winlist/module.desktop \
	src/modules/fileman/module.desktop \
	src/modules/fileman_opinfo/module.desktop \
	src/modules/conf/module.desktop \
	src/modules/conf_wallpaper2/module.desktop \
	src/modules/conf_theme/module.desktop \
	src/modules/conf_intl/module.desktop \
	src/modules/conf_applications/module.desktop \
	src/modules/conf_display/module.desktop \
	src/modules/conf_shelves/module.desktop \
	src/modules/conf_keybindings/module.desktop \
	src/modules/conf_edgebindings/module.desktop \
	src/modules/conf_window_remembers/module.desktop \
	src/modules/conf_window_manipulation/module.desktop \
	src/modules/conf_menus/module.desktop \
	src/modules/conf_dialogs/module.desktop \
	src/modules/conf_performance/module.desktop \
	src/modules/conf_paths/module.desktop \
	src/modules/conf_interaction/module.desktop \
	src/modules/msgbus/module.desktop \
	src/modules/conf_randr/module.desktop \
	src/modules/gadman/module.desktop \
	src/modules/mixer/module.desktop \
	src/modules/connman/module.desktop \
	src/modules/illume2/doc/illume.dox \
	src/modules/illume2/module.desktop \
	src/modules/illume-home/module.desktop \
	src/modules/illume-home-toggle/module.desktop \
	src/modules/illume-softkey/module.desktop \
	src/modules/illume-keyboard/module.desktop \
	src/modules/illume-indicator/module.desktop \
	src/modules/illume-kbd-toggle/module.desktop \
	src/modules/illume-mode-toggle/module.desktop \
	src/modules/illume-bluetooth/module.desktop \
	src/modules/syscon/module.desktop \
	src/modules/everything/module.desktop \
	src/modules/everything/everything.pc \
	src/modules/systray/module.desktop \
	src/modules/comp/module.desktop \
	src/modules/physics/module.desktop \
	src/modules/quickaccess/module.desktop \
	src/modules/shot/module.desktop \
	src/modules/backlight/module.desktop \
	src/modules/tasks/module.desktop \
	src/modules/xkbswitch/module.desktop \
	src/modules/tiling/module.desktop \
	src/modules/access/module.desktop
CONFIG_CLEAN_VPATH_FILES =
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(filesdir)" "$(DESTDIR)$(pkgconfigdir)"
DATA = $(files_DATA) $(pkgconfig_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = src data doc config po
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
DIST_TARGETS = dist-bzip2 dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/jeff/bodhi_debs/20150407/e17-20150407/missing aclocal-1.14
ALLOCA = 
ALL_LINGUAS = bg ca cs da de el eo es fi fr fr_CH he hu it ja ko nb nl pl pt_BR ru sk sl sv tr zh_CN zh_TW
ALSA_CFLAGS = -I/usr/include/alsa  
ALSA_LIBS = -lasound  
ALSA_VERSION = 1.0.27.2
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
AUTOCONF = ${SHELL} /home/jeff/bodhi_debs/20150407/e17-20150407/missing autoconf
AUTOHEADER = ${SHELL} /home/jeff/bodhi_debs/20150407/e17-20150407/missing autoheader
AUTOMAKE = ${SHELL} /home/jeff/bodhi_debs/20150407/e17-20150407/missing automake-1.14
AWK = mawk
BATTERY_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eet-1  
BATTERY_LDFLAGS = 
BATTERY_LIBS = -lecore -lecore_file -lecore_con -leina -lpthread  
BATTERY_VERSION = 
CC = gcc -std=gnu99
CCDEPMODE = depmode=none
CFLAGS = -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wshadow -Wall -W
CPP = gcc -E
CPPFLAGS = -D_FORTIFY_SOURCE=2
CYGPATH_W = echo
DBUS_MOUNT_CONFIG = 1
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
ECONNMAN_CFLAGS = -pthread -I/usr/include/e_dbus-1 -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eo-1  
ECONNMAN_LIBS = -ledbus -ldbus-1  
ECONNMAN_VERSION = 
ECORE_IMF_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ecore-imf-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/ecore-imf-evas-1 -I/usr/include/evas-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eet-1 -I/usr//include/luajit-2.0  
ECORE_IMF_LIBS = -lecore_imf -lecore_imf_evas  
ECORE_IMF_VERSION = 
EDJE_DEF = -DLOWRES_PDA=1 -DMEDIUMRES_PDA=2 -DHIRES_PDA=3 -DSLOW_PC=4 -DMEDIUM_PC=5 -DFAST_PC=6 -DE17_PROFILE=SLOW_PC
EET_CFLAGS = -I/usr/include/efl-1 -I/usr/include/eet-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina  
EET_LIBS = -leet  
EEZE_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/eet-1 -I/usr/include/ecore-con-1 -I/usr/include/ecore-file-1 -I/usr/include/eo-1 -I/usr/include/ecore-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  
EEZE_LIBS = -leeze -lecore -leina -lpthread  
EEZE_MOUNT_CONFIG = 0
EGREP = /bin/grep -E
ELM_CFLAGS = -pthread -D_REENTRANT -I/usr/include/elementary-1 -I/usr/include/efl-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eet-1 -I/usr/include/evas-1 -I/usr/include/ecore-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-input-1 -I/usr/include/edje-1 -I/usr/include/eo-1 -I/usr/include/ethumb-client-1 -I/usr/include/emotion-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-con-1 -I/usr/include/eio-1 -I/usr/include/eldbus-1 -I/usr/include/efreet-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr//include/luajit-2.0 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-audio-1 -I/usr/include/ephysics-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/bullet -I/usr/include/ethumb-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid  
ELM_LIBS = -lelementary -lefl -leina -lpthread -leet -levas -lecore -lecore_evas -lecore_file -lecore_input -ledje -leo -lethumb_client -lemotion -lecore_imf -lecore_con -leldbus -lefreet -lefreet_mime -lefreet_trash -leio -ldl -lm  
EMOTION_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/emotion-1 -I/usr/include/eeze-1 -I/usr/include/eio-1 -I/usr/include/evas-1 -I/usr/include/eet-1 -I/usr/include/ecore-1 -I/usr/include/eo-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/libmount -I/usr/include/ecore-con-1 -I/usr/include/ecore-file-1 -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr//include/luajit-2.0  
EMOTION_LIBS = -lemotion  
ENOTIFY_CFLAGS = -pthread -I/usr/include/e_dbus-1 -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eo-1 -I/usr/include/evas-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eet-1 -I/usr//include/luajit-2.0  
ENOTIFY_LIBS = -ledbus -ldbus-1 -lenotify  
ENOTIFY_VERSION = 
EPHYSICS_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ephysics-1 -I/usr/include/bullet -I/usr/include/eo-1 -I/usr/include/ecore-1 -I/usr/include/evas-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eet-1 -I/usr//include/luajit-2.0  
EPHYSICS_LIBS = -lephysics  
EPHYSICS_VERSION = 
EXEEXT = 
E_ALERT_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eo-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-con-1 -I/usr/include/eet-1  
E_ALERT_LIBS = -lxcb-shape -lxcb-keysyms -lxcb -leina -lpthread -lecore -lecore_ipc  
E_CFLAGS = -pthread -D_REENTRANT -I/usr/include/efl-1 -I/usr/include/evas-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eet-1 -I/usr/include/eo-1 -I/usr//include/luajit-2.0 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/ecore-x-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-con-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-file-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/ephysics-1 -I/usr/include/eio-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/bullet -I/usr/include/efreet-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/e_dbus-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid  
E_FM_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/efreet-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/e_dbus-1  
E_FM_CMDLINE_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eo-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eet-1 -I/usr/include/e_dbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  
E_FM_CMDLINE_LIBS = -leina -lpthread -lecore -lecore_file -ledbus -ldbus-1  
E_FM_LIBS = -lecore -lecore_file -lecore_ipc -leet -lefreet -leina -lpthread -lehal -ledbus -ldbus-1 -leukit  
E_FM_OPEN_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eet-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eo-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-con-1  
E_FM_OPEN_LIBS = -leina -lpthread -leet -lecore -lecore_ipc -lecore_con  
E_FM_OP_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eet-1  
E_FM_OP_LIBS = -lecore -lecore_file -leina -lpthread  
E_GRABBER_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eo-1 -I/usr/include/eet-1 -I/usr/include/efreet-1 -I/usr/include/eldbus-1 -I/usr/include/ecore-file-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/ecore-con-1 -I/usr/include/ecore-x-1 -I/usr/include/ecore-input-1  
E_GRABBER_LIBS = -leina -lpthread -lecore -leet -lefreet -lecore_x  
E_IMC_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ecore-file-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-1 -I/usr/include/ecore-con-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eet-1  
E_IMC_LIBS = -lecore_file -leet -leina -lpthread  
E_INIT_CFLAGS = -pthread -D_REENTRANT -I/usr/include/efl-1 -I/usr/include/evas-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eet-1 -I/usr/include/eo-1 -I/usr//include/luajit-2.0 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/ecore-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-x-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/ephysics-1 -I/usr/include/eio-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-file-1 -I/usr/include/bullet -I/usr/include/ecore-con-1 -I/usr/include/ecore-ipc-1  
E_INIT_LIBS = -levas -lecore -lecore_evas -lecore_x -ledje -lecore_ipc -leina -lpthread  
E_LIBS = -levas -lecore -lecore_x -lecore_evas -lecore_input -lecore_input_evas -lecore_con -lecore_ipc -lecore_file -leet -ledje -lefreet -lefreet_mime -lefreet_trash -leina -lpthread -leio -lehal -ledbus -ldbus-1 -leukit -leeze  
E_OPEN_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eo-1 -I/usr/include/efreet-1 -I/usr/include/eldbus-1 -I/usr/include/ecore-file-1 -I/usr/include/eet-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/ecore-con-1  
E_OPEN_LIBS = -leina -lpthread -lecore -lefreet -lefreet_mime  
E_REMOTE_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-con-1 -I/usr/include/eet-1  
E_REMOTE_LIBS = -lecore -lecore_ipc -leet -leina -lpthread  
E_START_CFLAGS = -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina  
E_START_LIBS = -leina -lpthread  
E_SYS_CFLAGS = -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina  
E_SYS_LIBS = -leina -lpthread  
E_THUMB_CFLAGS = -pthread -D_REENTRANT -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/evas-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eet-1 -I/usr/include/eo-1 -I/usr//include/luajit-2.0 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/ecore-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/ephysics-1 -I/usr/include/eio-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-file-1 -I/usr/include/bullet -I/usr/include/ecore-con-1 -I/usr/include/ecore-ipc-1 -I/usr/include/efreet-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  
E_THUMB_LIBS = -leina -lpthread -levas -lecore -lecore_evas -ledje -lecore_file -lecore_ipc -leet -lefreet  
FGREP = /bin/grep -F
GETTEXT_MACRO_VERSION = 0.18
GMSGFMT = /usr/bin/msgfmt
GMSGFMT_015 = /usr/bin/msgfmt
GREP = /bin/grep
HAVE_ALSA = yes
HAVE_BATTERY = yes
HAVE_ECONNMAN = yes
HAVE_ECORE_IMF = yes
HAVE_ENOTIFY = yes
HAVE_EPHYSICS = yes
HAVE_TEMPERATURE = yes
HIBERNATE = /etc/acpi/hibernate.sh force
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INTLLIBS = 
INTL_MACOSX_LIBS = 
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro
LIBICONV = -liconv
LIBINTL = 
LIBOBJS = 
LIBS =  -lpam
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LOCALE_DIR = /usr/share/locale
LTLIBICONV = -liconv
LTLIBINTL = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/jeff/bodhi_debs/20150407/e17-20150407/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
MODULE_ARCH = linux-gnu-x86_64-0.17.6
MSGFMT = /usr/bin/msgfmt
MSGFMT_015 = /usr/bin/msgfmt
MSGMERGE = /usr/bin/msgmerge
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = enlightenment
PACKAGE_BIN_DIR = ${exec_prefix}/bin
PACKAGE_BUGREPORT = enlightenment-devel@lists.sourceforge.net
PACKAGE_DATA_DIR = /usr/share/enlightenment
PACKAGE_LIB_DIR = ${prefix}/lib/x86_64-linux-gnu
PACKAGE_NAME = enlightenment
PACKAGE_STRING = enlightenment 0.17.6
PACKAGE_SYSCONF_DIR = /etc
PACKAGE_TARNAME = enlightenment
PACKAGE_URL = 
PACKAGE_VERSION = 0.17.6
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
POSUB = po
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
SOUND_CFLAGS = -I/usr/include/alsa   -DHAVE_ALSA 
SOUND_LIBS = -lasound   
STRIP = strip
SUID_CFLAGS = -fPIE
SUID_LDFLAGS = -pie
SUSPEND = /etc/acpi/sleep.sh force
TEMPERATURE_CFLAGS = -pthread -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eet-1  
TEMPERATURE_LIBS = -lecore -lecore_file -leina -lpthread  
TEMPERATURE_VERSION = 
USE_MODULE_ACCESS = false
USE_MODULE_BACKLIGHT = true
USE_MODULE_BATTERY = true
USE_MODULE_CLOCK = true
USE_MODULE_COMP = true
USE_MODULE_CONF = true
USE_MODULE_CONF_APPLICATIONS = true
USE_MODULE_CONF_DIALOGS = true
USE_MODULE_CONF_DISPLAY = true
USE_MODULE_CONF_EDGEBINDINGS = true
USE_MODULE_CONF_INTERACTION = true
USE_MODULE_CONF_INTL = true
USE_MODULE_CONF_KEYBINDINGS = true
USE_MODULE_CONF_MENUS = true
USE_MODULE_CONF_PATHS = true
USE_MODULE_CONF_PERFORMANCE = true
USE_MODULE_CONF_RANDR = true
USE_MODULE_CONF_SHELVES = true
USE_MODULE_CONF_THEME = true
USE_MODULE_CONF_WALLPAPER2 = false
USE_MODULE_CONF_WINDOW_MANIPULATION = true
USE_MODULE_CONF_WINDOW_REMEMBERS = true
USE_MODULE_CONNMAN = true
USE_MODULE_CPUFREQ = true
USE_MODULE_DROPSHADOW = true
USE_MODULE_EVERYTHING = true
USE_MODULE_FILEMAN = true
USE_MODULE_FILEMAN_OPINFO = true
USE_MODULE_GADMAN = true
USE_MODULE_IBAR = true
USE_MODULE_IBOX = true
USE_MODULE_ILLUME2 = true
USE_MODULE_MIXER = true
USE_MODULE_MSGBUS = true
USE_MODULE_NOTIFICATION = true
USE_MODULE_PAGER = true
USE_MODULE_PHYSICS = false
USE_MODULE_QUICKACCESS = true
USE_MODULE_SHOT = true
USE_MODULE_START = true
USE_MODULE_SYSCON = true
USE_MODULE_SYSTRAY = true
USE_MODULE_TASKS = true
USE_MODULE_TEMPERATURE = true
USE_MODULE_TILING = true
USE_MODULE_WINLIST = true
USE_MODULE_WIZARD = true
USE_MODULE_XKBSWITCH = true
USE_NLS = yes
VALGRIND_CFLAGS = 
VALGRIND_LIBS = 
VERSION = 0.17.6
WAYLAND_CFLAGS = 
WAYLAND_LIBS = 
XGETTEXT = /usr/bin/xgettext
XGETTEXT_015 = /usr/bin/xgettext
XGETTEXT_EXTRA_OPTIONS = 
abs_builddir = /home/jeff/bodhi_debs/20150407/e17-20150407
abs_srcdir = /home/jeff/bodhi_debs/20150407/e17-20150407
abs_top_builddir = /home/jeff/bodhi_debs/20150407/e17-20150407
abs_top_srcdir = /home/jeff/bodhi_debs/20150407/e17-20150407
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = x86_64-linux-gnu
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
cf_cflags = 
cf_libs = 
datadir = ${datarootdir}
datarootdir = ${prefix}/share
dlopen_libs = -ldl
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
e_cflags = -DUSE_E_CONFIG_H -pthread -D_REENTRANT -I/usr/include/efl-1 -I/usr/include/evas-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eet-1 -I/usr/include/eo-1 -I/usr//include/luajit-2.0 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/ecore-x-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-con-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-file-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/ephysics-1 -I/usr/include/eio-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/bullet -I/usr/include/efreet-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/e_dbus-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid   -pthread -I/usr/include/efl-1 -I/usr/include/ecore-imf-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/eo-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/ecore-imf-evas-1 -I/usr/include/evas-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/eet-1 -I/usr//include/luajit-2.0  
e_configflags = -DUSE_E_CONFIG_H
e_libs = -levas -lecore -lecore_x -lecore_evas -lecore_input -lecore_input_evas -lecore_con -lecore_ipc -lecore_file -leet -ledje -lefreet -lefreet_mime -lefreet_trash -leina -lpthread -leio -lehal -ledbus -ldbus-1 -leukit -leeze     -lecore_imf -lecore_imf_evas   
edje_cc = /usr/bin/edje_cc
eet_eet = /usr/bin/eet
efl_doxygen = doxygen
efl_have_doxygen = yes
efl_version = 1.7.10
exec_prefix = ${prefix}
fnmatch_libs = 
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${prefix}/share/info
install_sh = ${SHELL} /home/jeff/bodhi_debs/20150407/e17-20150407/install-sh
libdir = ${prefix}/lib/x86_64-linux-gnu
libexecdir = ${prefix}/lib/x86_64-linux-gnu
localedir = ${datarootdir}/locale
localstatedir = /var
mandir = ${prefix}/share/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
release = 0.17.6
release_info = 
requirements_e = evas >= 1.7.10 ecore >= 1.7.10 ecore-x >= 1.7.10 ecore-evas >= 1.7.10 ecore-con >= 1.7.10 ecore-ipc >= 1.7.10 ecore-file >= 1.7.10 eet >= 1.7.10 edje >= 1.7.10 efreet >= 1.7.10 efreet-mime >= 1.7.10 efreet-trash >= 1.7.10 eina >= 1.7.10 dbus-1 edbus >= 1.7.10 eio >= 1.7.10 ehal >= 1.7.10, edbus >= 1.7.10 eukit >= 1.7.10  eeze elementary >= 1.7.10 emotion >= 1.7.10
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = /etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
version_info = 17:6:17
SUBDIRS = src data doc config $(am__append_1)
ACLOCAL_AMFLAGS = -I m4 ${ACLOCAL_FLAGS}
MAINTAINERCLEANFILES = ABOUT-NLS* Makefile.in aclocal.m4 compile \
	config.guess config.h.in config.h.in~ config.rpath config.sub \
	configure depcomp install-sh ltmain.sh missing \
	$(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz \
	$(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.bz2 \
	$(PACKAGE_TARNAME)-$(PACKAGE_VERSION)-doc.tar.bz2 \
	m4/libtool.m4 m4/lt~obsolete.m4 m4/ltoptions.m4 m4/ltsugar.m4 \
	m4/ltversion.m4 m4/codeset.m4 m4/gettext.m4 m4/glibc21.m4 \
	m4/iconv.m4 m4/intdiv0.m4 m4/inttypes_h.m4 m4/inttypes.m4 \
	m4/inttypes-pri.m4 m4/isc-posix.m4 m4/lcmessage.m4 \
	m4/lib-ld.m4 m4/lib-link.m4 m4/lib-prefix.m4 m4/nls.m4 \
	m4/po.m4 m4/progtest.m4 m4/stdint_h.m4 m4/uintmax_t.m4 \
	m4/ulonglong.m4 $(am__append_2)
EXTRA_DIST = config.rpath  README AUTHORS COPYING \
             enlightenment.spec.in enlightenment.spec enlightenment.pc

filesdir = $(datadir)/enlightenment/
files_DATA = AUTHORS COPYING 
pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = enlightenment.pc
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
enlightenment.spec: $(top_builddir)/config.status $(srcdir)/enlightenment.spec.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
enlightenment.pc: $(top_builddir)/config.status $(srcdir)/enlightenment.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/ibar/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/ibar/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/dropshadow/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/dropshadow/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/clock/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/clock/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/pager/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/pager/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/battery/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/battery/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/temperature/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/temperature/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/notification/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/notification/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/cpufreq/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/cpufreq/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/ibox/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/ibox/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/start/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/start/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/winlist/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/winlist/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/fileman/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/fileman/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/fileman_opinfo/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/fileman_opinfo/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_wallpaper2/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_wallpaper2/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_theme/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_theme/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_intl/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_intl/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_applications/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_applications/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_display/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_display/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_shelves/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_shelves/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_keybindings/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_keybindings/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_edgebindings/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_edgebindings/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_window_remembers/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_window_remembers/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_window_manipulation/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_window_manipulation/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_menus/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_menus/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_dialogs/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_dialogs/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_performance/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_performance/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_paths/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_paths/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_interaction/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_interaction/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/msgbus/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/msgbus/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/conf_randr/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/conf_randr/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/gadman/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/gadman/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/mixer/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/mixer/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/connman/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/connman/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume2/doc/illume.dox: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume2/doc/illume.dox.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume2/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume2/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-home/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-home/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-home-toggle/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-home-toggle/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-softkey/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-softkey/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-keyboard/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-keyboard/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-indicator/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-indicator/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-kbd-toggle/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-kbd-toggle/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-mode-toggle/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-mode-toggle/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/illume-bluetooth/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/illume-bluetooth/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/syscon/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/syscon/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/everything/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/everything/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/everything/everything.pc: $(top_builddir)/config.status $(top_srcdir)/src/modules/everything/everything.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/systray/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/systray/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/comp/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/comp/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/physics/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/physics/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/quickaccess/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/quickaccess/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/shot/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/shot/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/backlight/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/backlight/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/tasks/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/tasks/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/xkbswitch/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/xkbswitch/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/tiling/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/tiling/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/modules/access/module.desktop: $(top_builddir)/config.status $(top_srcdir)/src/modules/access/module.desktop.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-filesDATA: $(files_DATA)
	@$(NORMAL_INSTALL)
	@list='$(files_DATA)'; test -n "$(filesdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(filesdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(filesdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(filesdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(filesdir)" || exit $$?; \
	done

uninstall-filesDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(files_DATA)'; test -n "$(filesdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(filesdir)'; $(am__uninstall_files_from_dir)
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(DATA) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(filesdir)" "$(DESTDIR)$(pkgconfigdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-recursive

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-hdr \
	distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-filesDATA install-pkgconfigDATA

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-filesDATA uninstall-pkgconfigDATA

.MAKE: $(am__recursive_targets) all install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-cscope clean-generic \
	clean-libtool cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-filesDATA install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-pkgconfigDATA install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs installdirs-am \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-filesDATA \
	uninstall-pkgconfigDATA


.PHONY: doc

doc:
	@echo "entering doc/"
	$(MAKE) -C doc doc

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
