debian/tmp/usr/bin/enlightenment
debian/tmp/usr/bin/enlightenment_remote
debian/tmp/usr/bin/enlightenment_start
debian/tmp/usr/bin/enlightenment_imc
debian/tmp/usr/bin/enlightenment_fm usr/lib/enlightenment
debian/tmp/usr/bin/enlightenment_init usr/lib/enlightenment
debian/tmp/usr/bin/enlightenment_sys usr/lib/enlightenment
debian/tmp/usr/bin/enlightenment_thumb usr/lib/enlightenment
debian/tmp/usr/etc/enlightenment/sysactions.conf etc/enlightenment
debian/tmp/usr/lib/enlightenment/preload/e_precache.so
debian/tmp/usr/lib/enlightenment/modules/*/*/module.so
debian/tmp/usr/lib/enlightenment/modules/*/module.desktop
debian/tmp/usr/lib/enlightenment/modules/*/e-module-*.edj
debian/tmp/usr/lib/enlightenment/modules/battery/*/batget
debian/tmp/usr/lib/enlightenment/modules/cpufreq/*/freqset
debian/tmp/usr/lib/enlightenment/modules/temperature/*/tempget
