Document: e17
Title: Debian e17 Manual
Author: <insert document author here>
Abstract: This manual describes what e17 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/e17/e17.sgml.gz

Format: postscript
Files: /usr/share/doc/e17/e17.ps.gz

Format: text
Files: /usr/share/doc/e17/e17.text.gz

Format: HTML
Index: /usr/share/doc/e17/html/index.html
Files: /usr/share/doc/e17/html/*.html
