.TH ENLIGHTENMENT-CONFIG 1 "May 1, 2008" enlightenment
.SH NAME
enlighenment-config \- get and set informations about installed enlightenment
.SH SYNOPSIS
.B enlightenment-config
[\fIOPTION\fR] ...
.br
.SH DESCRIPTION
Provides information about the installed enlightenment (e17) program
.SH OPTION
Values for OPTION are:
.TP
\fB\-\-prefix[=DIR]\fR
print prefix. If DIR is given, set the prefix to DIR
.TP
\fB\-\-exec-prefix[=DIR]\fR
print path to directory containing executables. If DIR is given, set the prefix to DIR
.TP
\fB\-\-libs\fR
print library linking information
.TP
\fB\-\-cflags\fR
print preprocessor flags and compiler options
.TP
\fB\-\-modules-dir\fR
print installation patch of the modules
.TP
\fB\-\-help\fR
print this help and exit
.TP
\fB\-\-version\fR
print version information
.SH BUGS
To report a bug, please visit \fIhttp://bugs.enlightenment.org/\fR
.SH AUTHOR
.TP
enlightenment was written by the Enlightenment Development Team
.I http://web.enlightenment.org
.PP
This manual page was written by Albin Tonnerre <albin.tonnerre@gmail.com>
for the Debian project (but may be used by others).
