.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ENLIGHTENMENT 1 "May 1, 2008" enlightenment
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
enlightenment \- This is just a placeholder until real man page has been written
.SH SYNOPSIS
.B enlightenment
[\fIOPTION\fR] ...
.SH DESCRIPTION
.PP
\fBenlightenment\fP does not have a man page yet.
.SH OPTIONS
.\"These programs follow the usual GNU command line syntax, with long
.\"options starting with two dashes (`-').
.\"A summary of options is included below.
.\"For a complete description, see the Info files.
.SH SEE ALSO
.SH AUTHOR
enlightenment was written by the Enlightenment Development Team
.I http://web.enlightenment.org
.PP
This manual page was written by Albin Tonnerre <albin.tonnerre@gmail.com>
for the Debian project (but may be used by others).
